### ISSUE TITLE
Try to implement more nicely css

### ISSUE THREAD

**Issue by eladcandroid** [JonathanDn/vue-dropdown#1]
Like this one:
https://codepen.io/j0be/pen/jWGVvV

**Comment by JonathanDn** [comment]
Good idea thanks! Will get to it soon

**Comment by JonathanDn** [comment]
Uploaded latest v1.0.3 of the dropdown with similar expanding animation, let me know what you think!

**Comment by eladcandroid** [comment]
Great improvement! 
I think that in order to make it more slick you still need to change the font, remove border etc. like in the codepen example...  also change the arrow in an open mode

**Comment by JonathanDn** [comment]
I agree, it makes it more of a micro-interaction component than a regular dropdown.

I will upgrade accordingly soon, thanks for the tips!

You think I should add a boolean option to reverse the dropdown to a regular "idle" dropdown?

**Comment by JonathanDn** [comment]
Hey @eladcandroid , i Just Updated everything with the requested modifications - enjoy :) 
Let me know if you are using it and if you need more capabilities, more properties etc?
