### ISSUE TITLE
Cannot find stylesheet to import

### ISSUE THREAD

**Issue by DavidShineHub** [JonathanDn/vue-dropdown#10]
You're trying to import the 'vue-dropdown' stylesheet but that doesn't exist.
You did fix this in a recent commit by changing the import to 'dropdown' but changed it back to 'vue-dropdown' in the commit after that

**Comment by DPC15038** [comment]
Also having this issue. Change `@import "./vue-dropdown";` to `@import "./dropdown";` in your `dropdown.vue` file. Would love to use this in my project, but can't until this is fixed.

**Comment by EricRouach** [comment]
Same here!
Thank you very much.

**Comment by JonathanDn** [comment]
@EricRouach  @DPC15038  @DavidShineHub  Hey Guys Sorry I wasn't available I will resolve this soon thank you for reporting the issue!

**Comment by JonathanDn** [comment]
@EricRouach  @DPC15038  @DavidShineHub  This issue is now resolved in npm version 1.0.12 just updated the package. Thanks again for notifying!
