### ISSUE TITLE
File to import not found or unreadable: ./vue-dropdown

### ISSUE THREAD

**Issue by fritzfr** [JonathanDn/vue-dropdown#11]
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

	@import "./vue-dropdown";
^
      File to import not found or unreadable: ./vue-dropdown.
      in /PROJECTFOLDER/node_modules/vue-dynamic-dropdown/dropdown.vue (line 152, column 1)
```

**Comment by Janluke0** [comment]
dude, read old issues before open another one #10 

@JonathanDn  can you fix it?

**Comment by JonathanDn** [comment]
@felix-voicehub  This issue indeed seems to relate to #10  Thank you for reporting I will resolve this soon.

**Comment by JonathanDn** [comment]
@felix-voicehub  @Janluke0   Issue just got resolved and updated, please use npm package version 1.0.12
