### ISSUE TITLE
Try to move style to computed

### ISSUE THREAD

**Issue by tranlehaiquan** [JonathanDn/vue-dropdown#2]
This style attribute look so long, can you try to move it to computed?
https://github.com/JonathanDn/vue-dropdown/blob/master/dropdown.vue#L6

**Comment by JonathanDn** [comment]
Good suggestion thank you @tranlehaiquan , I will get to it soon and upate

**Comment by JonathanDn** [comment]
Just resolved this issue - moved inline binded styles to a computed prop - "computedStyles"
