### ISSUE TITLE
Package does not work with baseline CLI Vue App

### ISSUE THREAD

**Issue by karnthis** [JonathanDn/vue-dropdown#7]
The Package gives compile errors when following install/getting started directions as written. The following are prerequisites due to use of SASS:
- sass-loader
- node-sass
- style-loader

Compile was successful for me after dev saving the above. Please add these as listed prereqs, or add to the install. I can submit a PR for the above if desired.

**Comment by JonathanDn** [comment]
Hey @karnthis  You are more then welcome to open a PR for this 👍

**Comment by JonathanDn** [comment]
This issue is resolved as you opened a PR and it was merged good job!
